server:
  port: 9587
spring:
  datasource:
    hikari:
      master:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/boltloan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
      slave:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbcUrl: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=TestDB
        username: SA
        password: <1234567890@Passw0rd>
#mybatis-plus
mybatis-plus:
  type-aliases-package: com.mumu.model
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty


